### ISSUE TITLE
Make fails due to non-ascii character

### ISSUE THREAD

**Issue by abrown41** [gtribello/mathNET#2]
After installing graphviz (perhaps this should be listed as a dependency in the README?) The make command failed with the following error:

```
python ../Scripts/createTopicPage.py ADSORPTION.xml ../
File "../Scripts/createTopicPage.py", line 86
SyntaxError: Non-ASCII character 'xc2' in file ../Scripts/createTopicPage.py on line 86, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
make[1]: *** [../html/ADSORPTION.html] Error 1
make: *** [topics] Error 2
```

However line 86 contains only a comment, so I can't fix the problem trivially.

**Comment by gtribello** [comment]
Firstly yes perhaps I should also write a README. ;-)

With regards to the xc2 I think this is something to do with # signs which are not always understood on different computers.  I don't really understand?  Anyway, as these # signs are for comments you can just delete the rogue comments and try again
